title: Hao Zhang's Homepage
page-top-title: Hao Zhang
top-section-bg-text: "Computer Science and Electrical Engineering \n AI for Healthcare" 
home-subtitle: Hao Zhang&ensp;|&ensp;张昊
copyright-text: '&copy; Hao Zhang 2024-2025. All Rights Reserved.'
